name: C/C++ CI

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: apt
      run: sudo apt-get update && sudo apt-get install wget curl    speech-dispatcher    libgstreamer-plugins-base1.0-dev     libgstreamer1.0-0:amd64     libgstreamer1.0-dev     libudev-dev android-sdk
    - name: configure
      env: 
        JOBS: 4
        SHADOW_BUILD_DIR: /tmp/shadow_build_dir
        CODESIGN: nocodesign
        SPEC: android-clang
        CONFIG: installer
        BITNESS: 64
        GSTREAMER_NAME: arm64
      run: |
        set -o xtrace
        git submodule update --init --recursive
        
        export sdk_version=sdk-tools-linux-4333796.zip
        
        #sudo mkdir -p ${ANDROID_SDK_ROOT} 
        #sudo curl --silent --show-error --location --fail --retry 3 --output /tmp/${sdk_version} https://dl.google.com/android/repository/${sdk_version} 
        #sudo unzip -q /tmp/${sdk_version} -d ${ANDROID_SDK_ROOT} 
        #sudo rm /tmp/${sdk_version}
        
        #mkdir ~/.android && echo '### User Sources for Android SDK Manager' > ~/.android/repositories.cfg
        #sudo yes | sdkmanager --licenses && sdkmanager --update
        
        #sudo sdkmanager "build-tools;28.0.3"
        
        wget --quiet https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/gstreamer-1.0-android-${GSTREAMER_NAME}-1.14.4.tar.bz2 
        tar jxf gstreamer-1.0-android-${GSTREAMER_NAME}-1.14.4.tar.bz2 
        ls -al
        ls -al gstreamer-1.0-android-universal-1.14.4
        
        wget --quiet https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip 
        unzip android-ndk-r20-linux-x86_64.zip > /dev/null
        export ANDROID_NDK_ROOT=`pwd`/android-ndk-r20 
        #export ANDROID_SDK_ROOT=/usr/local/android-sdk 
        export PATH=`pwd`/android-ndk-r20:$PATH        
        
        wget --quiet https://s3-us-west-2.amazonaws.com/qgroundcontrol/dependencies/Qt5.12.6-android_arm64_v8a-min.tar.bz2 
        tar jxf Qt5.12.6-android_arm64_v8a-min.tar.bz2 -C /tmp 
        export PATH=/tmp/Qt5.12-android_arm64_v8a/5.12.6/android_arm64_v8a/bin:$PATH
        
        #git remote set-branches origin 'master' 
        #git fetch --tags origin master 
        ./tools/update_android_version.sh ${BITNESS} master
        
        mkdir ${SHADOW_BUILD_DIR} && cd ${SHADOW_BUILD_DIR}
        
        export STABLE_OR_DAILY=StableBuild;   
        
        rm -rf gstreamer-1.0-android-armv7-1.5.2
        
        qmake -r $GITHUB_WORKSPACE/qgroundcontrol.pro CONFIG+=${CONFIG} CONFIG+=thread CONFIG+=${STABLE_OR_DAILY} CONFIG+=${CODESIGN} -spec ${SPEC}
        make VERBOSE=1 -j8 install || true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: release.zip
        # A file, directory or wildcard pattern that describes what to upload
        path: /tmp/shadow_build_dir/release/android-build/build/outputs/
